### ISSUE TITLE
Prevent admin user deletion

### ISSUE THREAD

**Issue by ltagliamonte** [eko/authz#208]
Currently it is possible to delete the admin user, effectively making an installation useless.
Would be nice to have a check to prevent the admin user to be deleted.

Steps to reproduce:
- login
- select User tab
- select `Bin` icon next to admin user
- select `Ok`

**Comment by eko** [comment]
I understand your point.

On the other hand, I think it's useful to let people that have access to the `delete` action on `authz.users` resource to delete it because in some cases, you will want to: for instance if you only want to use a service account authentication and/or SSO and don't want to keep a simple username/password authentication.

I think permissions are here to manage these cases so I propose to keep this feature as it is for now.

What do you think?

**Comment by eko** [comment]
After thinking more about this: I've added a security to avoid user auto-deleting itself. So the user admin cannot delete the admin user.

I think it fixes this issue so I close this issue for now.

Thank you
